### ISSUE TITLE
InfluxDB: Metrics not being partitioned properly

### ISSUE THREAD

**Issue by eripa** [sitespeedio/sitespeed.io#1385]
As reported in #1361 the Metric when using InfluxDB are not stored in a good way. Excuse my terminology, but each metric is saved in one long complete series.

Please note that I base this on Grafana usage.

With the default Graphite database I can easily query on different levels and replace parts with a variable or wildcard, for example:

`sitespeed_io.default.pageSummary.$site._.*.native.browsertime.statistics.timings.fullyLoaded.mean`

However, since all metrics are saved in one chunk in InfluxDB, there doesn't seem to be a way to make queries more dynamic. So to achieve the same result as the Graphite example above, I would need a couple of queries:

`pageSummary.example_com._.browsertime.statistics.timings.fullyLoaded.mean`
`pageSummary.example_com._.browsertime.statistics.timings.fullyLoaded.mean`
`pageSummary.foobar_com._.browsertime.statistics.timings.fullyLoaded.mean`
`pageSummary.foobar_com._.browsertime.statistics.timings.fullyLoaded.mean`

Also it seems like all parts are not present, like browser. 

----

Tested using Docker container: **sitespeedio/sitespeed.io:4.1.3**

```
version: '2'
services:
  influxdb:
    image: influxdb:alpine
    volumes:
      - ./influxdb-lib-data:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    restart: always
    command: influxd -config /etc/influxdb/influxdb.conf
  graphite:
    image: sitespeedio/graphite
    volumes:
      - ./graphite-data:/opt/graphite/storage/whisper
      - ./storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
      - ./storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
```
and a grafana container

`docker run --rm --net=container:sitespeed_influxdb_1 sitespeedio/sitespeed.io:4.1.3 https://example.com -b firefox --plugins.load influxdb --influxdb.host influxdb --influxdb.database sitespeed`
