### ISSUE TITLE
Error: Tried to add NaN to stats for path expireStats

### ISSUE THREAD

**Issue by hunt3r** [sitespeedio/sitespeed.io#1747]
Hello,

First, thank you for such a high quality FOSS project. I was about to build a very inferior version by wrapping lighthouse in some aggregation/Dashboarding before I stumbled onto this.  Although you guys may want to check out lighthouse for aggregation at some point.

Anyways, I'm running into this error on some of my URLs and some of my metrics end up empty on the dashboard. I haven't been running the dashboard for long so it may very well be expected that some metrics are empty for a while, but this error concerns me.

```
[2017-10-18 17:51:00] INFO: 112 requests, 2421.92 kb, backEndTime: 1.26s (±539.20ms), firstPaint: 1.63s (±550.07ms), DOMContentLoaded: 2.91s (±592.23ms), Load: 4.58s (±582.66ms), rumSpeedIndex: 1632 (±549.11) (3 runs)
[2017-10-18 17:51:00] ERROR: Error: Tried to add NaN to stats for path expireStats
    at Object.pushStats (/usr/src/app/lib/support/statsHelpers.js:27:13)
    at Object.pushGroupStats (/usr/src/app/lib/support/statsHelpers.js:35:10)
    at asset (/usr/src/app/lib/plugins/coach/pagexrayAggregator.js:81:22)
    at arrayEach (/usr/src/app/node_modules/lodash.foreach/index.js:35:9)
    at forEach (/usr/src/app/node_modules/lodash.foreach/index.js:290:10)
    at /usr/src/app/lib/plugins/coach/pagexrayAggregator.js:80:7
    at Array.forEach (native)
    at Object.addToAggregate (/usr/src/app/lib/plugins/coach/pagexrayAggregator.js:19:17)
    at Object.processMessage (/usr/src/app/lib/plugins/coach/index.js:104:28)
    at queue.process.message (/usr/src/app/lib/support/queueHandler.js:192:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

Example dashboard:
![image](https://user-images.githubusercontent.com/324819/31734293-401095de-b40c-11e7-95c3-69eb68157e26.png)

Is this something you have seen before?

I'm running on docker compose (Which by the way I had to revert to the previous version of the docker compose file because version 3 was breaking. 

```
docker-compose --version
docker-compose version 1.16.1, build 6d1ac21
```
As you see from above I'm running the latest docker-compose 1.16.1

My Docker compose yml
```
version: '2'
services:
    sitespeed.io:
      image: sitespeedio/sitespeed.io
      command: -V
      privileged: true
      shm_size: 2g
      volumes:
            - ./sitespeed-result/:/sitespeed.io/sitespeed-result
            - ./sites:/sitespeed.io/sites
            - ./urls.txt:/sitespeed.io/urls.txt
    grafana:
      image: grafana/grafana:4.5.1
      depends_on:
        - graphite
      links:
        - graphite
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=hdeAga76VG6ga7plZ1
        - GF_SECURITY_ADMIN_USER=sitespeedio
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_USERS_ALLOW_ORG_CREATE=false
      volumes:
        - grafana:/var/lib/grafana
      restart: always
    graphite:
      image: sitespeedio/graphite
      ports:
        - "2003:2003"
        - "8080:80"
      restart: always
      volumes:
        - graphite:/opt/graphite/storage/whisper
    grafana-setup:
      image: sitespeedio/grafana-bootstrap:sitespeed.io-4.6
      links:
        - grafana
      environment:
        - GF_PASSWORD=hdeAga76VG6ga7plZ1
        - GF_USER=sitespeedio
volumes:
    grafana:
    graphite:
```

Again, when I ran the latest iteration I could never get any stats to show up, but the sites would show up in the dropdown. Reverting to the previous version remedied that. 

UPDATE: I actually had to revert all the way back to 
https://raw.githubusercontent.com/sitespeedio/sitespeed.io/17db0ae25bdfddaf6248a4c06a9f87cf2e1c38ac/docker/docker-compose.yml 

To get it fully working for me on OSX.
OSX Sierra: 10.12.6 (16G29)

But now I'm actually seeing graphs and all numbers populated.

Thanks again and let me know what other info would be useful.
