### ISSUE TITLE
Json output format support

### ISSUE THREAD

**Issue by george-haddad** [sitespeedio/sitespeed.io#2216]
It would be great to have `json` format as an option for the budget output. Currently there is only `tap` and `junit xml` which are great when integrating with tools that read those. Having `json` format makes it easier to integrate with `nodejs`. A good use case would be as follows:

- Run site speed docker with budget config file
- Set output format to `json`
- Set output folder to a directory your scripts can access
- When test is done, run a node app to read the `json` results
- Make assertions with a test framework like `jest`, `mocha`, `chai` ...etc.

The below is how a circleci integration test would look like if I wanted to run a test throttled to 3g and have the results outputted to a `json` file so that I can read it from a nodejs test suite and run the numbers through tests that I create. This is as opposed to having the entire process exit with code 1 when 1 out of many items fail the budget and one has to look at an html, junit or tap file.

```yaml
  test-performance-sitespeed:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo modprobe ifb numifbs=1
      - run: docker run --cap-add=NET_ADMIN --shm-size=1g --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io:7.7.2 -c 3g --browsertime.connectivity.engine=throttle -n 1 --budget.configPath perf-budget.json --budget.output json --outputFolder ./sitespeed-results https://www.sitespeed.io/
      - run: npm run test:sitespeed
```
