### ISSUE TITLE
Several Questions - Cost, Back Ups, Missing Data

### ISSUE THREAD

**Issue by gety9** [sitespeedio/sitespeed.io#2246]
Guys hi,

First of all thank you for sitespeed.io! Was playing with it all day today - great product!

I have couple of newbie questions:
1 (COST) 
I read your comment on cost and recommendation of AWS instance C4.large, but you do 119 runs per hour.
If we have just 1 site (~5 urls) to test, and want to run it once a day, can we use smaller server? Like digital ocean smallest droplet (1 GB / 1 CPU / 25 GB SSD) ?

2 (Back Ups/Transfer)
In the case if we will need to transfer graphite data to another server, where all data is stored? `graphite.db` ?

3 (Missing Data)
I just did couple of test runs, and in [your example](https://puu.sh/CuJCD/dcb7e2a7b5.png) Page Summary Shows Heading, LargestImage and CPU Data. However [i don't see them](https://puu.sh/CuJE6/f15347e725.png). What am i doing wrong?

Commands i run:
`docker-compose up -d`
`docker-compose run sitespeed.io https://en.wikipedia.org/wiki/Barack_Obama/ --graphite.host=graphite`

Docker compose:
```
version: '3'
services:
    sitespeed.io:
      image: sitespeedio/sitespeed.io
      command: -V
      shm_size: 1g
      volumes:
            - ./sitespeed-result/:/sitespeed.io/sitespeed-result
    grafana:
      image: grafana/grafana:5.4.0
      depends_on:
        - graphite
      links:
        - graphite
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=hdeAga76VG6ga7plZ1
        - GF_SECURITY_ADMIN_USER=sitespeedio
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_USERS_ALLOW_ORG_CREATE=false
      volumes:
        - grafana:/var/lib/grafana
      restart: always
    graphite:
      image: sitespeedio/graphite:1.0.2-2-b
      ports:
        - "2003:2003"
        - "8080:80"
      restart: always
      volumes:
        - whisper:/opt/graphite/storage/whisper
        - ./graphite/graphite.db:/opt/graphite/storage/graphite.db
        - ./graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        - ./graphite/conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
        - ./graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf
    grafana-setup:
      image: sitespeedio/grafana-bootstrap:7.5
      links:
        - grafana
      environment:
        - GF_PASSWORD=hdeAga76VG6ga7plZ1
        - GF_USER=sitespeedio
volumes:
    grafana:
    whisper:
```

4(Lighthouse/GPSI and Graphite/Grafana)
When using -plus1 version of image i see Lighthouse/GPSI results [in html reports](https://puu.sh/CuM8X/e037d7b4ab.png). But don't see them in Grafana dashboard. Where are they displayed?

Using same docker-compose, just replaced image with
`      image: sitespeedio/sitespeed.io:7.7.3-plus1 
`
