### ISSUE TITLE
Advice on running the docker image in concourse ci

### ISSUE THREAD

**Issue by mbulfair** [sitespeedio/sitespeed.io#2517]
This is more a question, 
I am using [concourse CI](https://concourse-ci.org) and I set up a job with the docker image as shown

```yml
---
platform: linux
inputs:
  - name: source-repo
outputs:
  - name: reports
image_resource:
  type: docker-image
  source:
    repository: sitespeedio/sitespeed.io
    tag: "latest"
run:
  path: ./ci/tasks/sitespeedio.sh
  dir: ./source-repo
```

While the job get's the image, what command do I run inside the image to trigger the tests. I am not sure if this is even the right way. 

Thank you.
