### ISSUE TITLE
PageIndex out of range

### ISSUE THREAD

**Issue by cambiph** [sitespeedio/sitespeed.io#2941]
Hey,

I am running the latest sitespeed docker image (INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.13.0 sitespeed.io: 12.2.2 browsertime: 8.2.0 coach: 5.0.0) against a small demo-app. The testrun uses the following config:

```json
{
    "browsertime": {
        "browser": "chrome"
    },
    "budget": {
        "configPath": "/sitespeed.io/config/budget.json",
        "output": "junit"
    },
    "outputFolder": "results/chrome"
}
```

The docker-compose file is as follows:

```yaml
version: "3"
services:
  sitespeed-chrome:
    image: ${DOCKER_REGISTRY}sitespeedio/sitespeed.io
    command: "--config ./config/config-chrome.json --preScript ./scripts/preScript.js http://demo.app.io:8080/demo/performance.html"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy}
    shm_size: 2g
    volumes:
      - ./performance/config:/sitespeed.io/config/
      - ./performance/scripts:/sitespeed.io/scripts/  
      - ./performance/results/chrome/:/sitespeed.io/chrome-results/
  demo.app.io:
    image: ${DOCKER_REGISTRY}node:12
    container_name: demo.app.io
    hostname: demo.app.io
    working_dir: /home/node/app
    entrypoint: bash -c "npm install && npm run demo"
    volumes:
      - .:/home/node/app

```

The preScript looks like this:
```javascript
const http = require('http');

module.exports = async function (context, commands) {

    const hostname = 'demo.app.io';
    const port = '8080';
    const path = 'demo/performance.html';

    async function areDemoComponentsPresent() {
        await commands.navigate(`http://${hostname}:${port}/${path}`);
        const webdriver = context.selenium.webdriver;
        const driver = context.selenium.driver;
        const demos = await driver.findElements(webdriver.By.css('.demo'));
        return demos.length > 0;
    }

    return new Promise(resolve => {
        function poll() {
            setTimeout(async () => {
                http.get(`http://${hostname}:${port}`, async (res) => {
                    const { statusCode } = res;
                    if (statusCode === 200) {
                        context.log.info(`App available on ${hostname}:${port}.`);
                        try {
                            const demoComponents = await areDemoComponentsPresent();
                            if (demoComponents) {
                                resolve();
                            } else {
                                throw e;
                            }
                        } catch (e){
                            throw e;
                        }
                    } else {
                        poll();
                    }
                }).on('error', () => {
                    context.log.error(`App not yet available on ${hostname}:${port}.`);
                    poll();
                });
            }, 5000);
        }

        poll();
    });
}
```

At the end of the last (third) iteration, sitespeed throws the following error:
```
sitespeed-chrome_1  | [2020-03-23 12:11:59] INFO: Testing url http://demo.app.io:8080/demo/performance.html iteration 3
sitespeed-chrome_1  | [2020-03-23 12:12:11] INFO: http://demo.app.io:8080/demo/performance.html BackEndTime: 10 DomInteractiveTime: 44 DomContentLoadedTime: 104 FirstPaint: 76 PageLoadTime: 136
sitespeed-chrome_1  | [2020-03-23 12:12:11] INFO: VisualMetrics FirstVisualChange: 108 SpeedIndex: 108 PerceptualSpeedIndex: 116 ContentfulSpeedIndex: 112 VisualComplete85: 108 LastVisualChange: 144
sitespeed-chrome_1  | [2020-03-23 12:12:11] ERROR: Could not add meta data to the HAR, miss page 0
sitespeed-chrome_1  | [2020-03-23 12:12:11] ERROR: Could not add meta data to the HAR, miss page 1
sitespeed-chrome_1  | [2020-03-23 12:12:11] ERROR: Could not add meta data to the HAR, miss page 2
sitespeed-chrome_1  | [2020-03-23 12:12:11] INFO: http://demo.app.io:8080/demo/performance.html backEndTime: 9ms (±0.54ms), firstPaint: 71ms (±2.68ms), firstVisualChange: 79ms (±11.79ms), DOMContentLoaded: 98ms (±3.84ms), Load: 121ms (±7.62ms), speedIndex: 79 (±11.79), perceptualSpeedIndex: 90 (±11.12), contentfulSpeedIndex: 84 (±11.49), visualComplete85: 79ms (±11.79ms), lastVisualChange: 125ms (±12.66ms), rumSpeedIndex: 71 (±2.68) (3 runs)
sitespeed-chrome_1  | [2020-03-23 12:12:11] ERROR: Could not find the right index 0 for har for url http://demo.app.io:8080/demo/performance.html 
sitespeed-chrome_1  | [2020-03-23 12:12:11] ERROR: Error: PageIndex out of range
sitespeed-chrome_1  |     at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
sitespeed-chrome_1  |     at Object.pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:83:12)
sitespeed-chrome_1  |     at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:230:29)
sitespeed-chrome_1  | [2020-03-23 12:12:11] INFO: Write junit budget to /sitespeed.io/results/chrome/junit.xml
sitespeed-chrome_1  | [2020-03-23 12:12:12] INFO: HTML stored in /sitespeed.io/results/chrome
```
As requested by @soulgalore on Slack, I am creating this issue.

Regards
