### ISSUE TITLE
Extrac space at the top of a file causes a problem

### ISSUE THREAD

**Issue by mephisto83** [sitespeedio/sitespeed.io#2944]
If i have a empty space before the javascript code, the results won't make it to the metrics.
If i remove the line space, then it works.

![image](https://user-images.githubusercontent.com/7797183/77685507-8b726280-6f69-11ea-8b28-435dad1048b2.png)

**Comment by soulgalore** [comment]
Hi @mephisto83 can you show me how you use it so I can reproduce? We have a couple of different ways to add JS.

**Comment by mephisto83** [comment]
```
docker-compose run sitespeed.io https://global-lmb2.renaissance-golabs.com/welcomeportal --script=./src/sitespeed.js --preScript=./src/pscript.js --script=./src/script.js  --script=./src/prescript.js --postScript=./src/postscript.js -v --graphite.host=graphite --graphite.namespace=lmb2.welcomeportal --graphite.annotationMessage="a message added 2" --html.showScript  --spa 
```

**Comment by mephisto83** [comment]
```
version: '3'
services:
    sitespeed.io:
      image: sitespeedio/sitespeed.io
      command: -V
      shm_size: 1g
      volumes:
            - ./sitespeed-result/:/sitespeed.io/sitespeed-result
            - D:/site_speed_tests/studentportal/src:/sitespeed.io/src
    grafana:
      image: grafana/grafana:6.6.2
      depends_on:
        - graphite
      links:
        - graphite
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=password
        - GF_SECURITY_ADMIN_USER=sitespeedio
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_USERS_ALLOW_SIGN_UP=true
        - GF_USERS_ALLOW_ORG_CREATE=true
      volumes:
        - grafana:/var/lib/grafana
      restart: always
    graphite:
      image: sitespeedio/graphite:1.1.5-12
      ports:
        - "2003:2003"
        - "8080:80"
      restart: always
      volumes:
        # In production you should configure/map these to your container
        # Make sure whisper and graphite.db/grafana.db lives outside your containerr
        # https://www.sitespeed.io/documentation/sitespeed.io/graphite/#graphite-for-production-important
        - whisper:/opt/graphite/storage/whisper
        # Download an empty graphite.db from https://github.com/sitespeedio/sitespeed.io/tree/master/docker/graphite
        # - D:/site_speed_tests/studentportal/graphite/graphite.db:/opt/graphite/storage/graphite.db
        # 
        # And put the configuration files on your server, configure them as you need
        # Download from https://github.com/sitespeedio/docker-graphite-statsd/tree/master/conf/graphite
        - D:/site_speed_tests/studentportal/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        - D:/site_speed_tests/studentportal/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
        # - /absolute/path/to/graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf
    grafana-setup:
      image: sitespeedio/grafana-bootstrap:12.1.0
      links:
        - grafana
      environment:
        - GF_PASSWORD=password
        - GF_USER=sitespeedio
volumes:
    grafana:
    whisper:

````
