### ISSUE TITLE
Can't set the password for grafana

### ISSUE THREAD

**Issue by mephisto83** [sitespeedio/sitespeed.io#2946]
I'm trying to log in to grafana as the admin, using the admin credentials specified in the yml file used to compose sitespeed graphite and grafana, but i'm not getting anywhere with this.

```
version: '3'
services:
    sitespeed.io:
      image: sitespeedio/sitespeed.io
      command: -V
      shm_size: 1g
      volumes:
            - ./sitespeed-result/:/sitespeed.io/sitespeed-result
            - D:/site_speed_tests/studentportal/src:/sitespeed.io/src
    grafana:
      image: grafana/grafana:6.6.2
      depends_on:
        - graphite
      links:
        - graphite
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=grafana
        - GF_SECURITY_ADMIN_USER=admin
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_USERS_ALLOW_SIGN_UP=true
        - GF_USERS_ALLOW_ORG_CREATE=true
      volumes:
        - grafana:/var/lib/grafana
        - ./grafana_script:/sitespeed.io/grafana_script
      restart: always
      command: bash -c "/sitespeed.io/grafana_script/script.sh"
    graphite:
      image: sitespeedio/graphite:1.1.5-12
      ports:
        - "2003:2003"
        - "8080:80"
      restart: always
      volumes:
        # In production you should configure/map these to your container
        # Make sure whisper and graphite.db/grafana.db lives outside your containerr
        # https://www.sitespeed.io/documentation/sitespeed.io/graphite/#graphite-for-production-important
        - whisper:/opt/graphite/storage/whisper
        # Download an empty graphite.db from https://github.com/sitespeedio/sitespeed.io/tree/master/docker/graphite
        - ./graphite/graphite.db:/opt/graphite/storage/graphite.db
        # 
        # And put the configuration files on your server, configure them as you need
        # Download from https://github.com/sitespeedio/docker-graphite-statsd/tree/master/conf/graphite
        - ./storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        - ./storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
        # - /absolute/path/to/graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf
    grafana-setup:
      image: sitespeedio/grafana-bootstrap:12.1.0
      links:
        - grafana
      environment:
        - GF_PASSWORD=grafana
        - GF_USER=admin
volumes:
    grafana:
    whisper:

```
![image](https://user-images.githubusercontent.com/7797183/77758384-dd19fc00-7000-11ea-8ebf-565898292d7a.png)
