### ISSUE TITLE
GitHub Actions integration documentation example is outdated

### ISSUE THREAD

**Issue by ogarling** [sitespeedio/sitespeed.io#3016]
Because of the outdated documentation I tried to create a working example with WebPageReplay and a performance budget included.
The use of WebPageReplay made it for me difficult to use the out-of-the-box "docker container running" because I was not able to provide the required Docker options.
Beneath my working, but probably not optimal code, to get it working. When the performance budget assertion fails however the step does not fail... (return code is not interpreted?)

```
name: run Sitespeed

on: [push]

jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running Sitespeed
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: running Sitespeed container with options and arguments
        run: docker run --cap-add=NET_ADMIN -e REPLAY=true -e LATENCY=100 -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:13.0.3-action https://www.sitespeed.io --budget.configPath .github/budget.json -n 1 
```
(please note that a .github/budget.json should be added to the repo)
