### ISSUE TITLE
Graphite in docker compose and running sitespeedio - cant'connect

### ISSUE THREAD

**Issue by mikkeschiren** [sitespeedio/sitespeed.io#3078]
I am struggling to get this to work - before I had sitespeed.io in docker-compsoe - now with the recommended way, I have only graphite and grafana in docker-compose (network application_default). 

Running:
```
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:13.3.2 --graphite.host=graphite --network=application_default https://www.sitespeed.io/
```

Give me
```
: Error: getaddrinfo ENOTFOUND graphite
```

I am using linux.

These are the settings for graphite in docker-compose:

```
    graphite:
      image: sitespeedio/graphite:1.1.5-12
      container_name: graphite 
      ports:
        - "2003:2003"
        - "8080:80"
      restart: always
```
