### ISSUE TITLE
How to mark test failed when budget fails in git pipeline

### ISSUE THREAD

**Issue by jakkshay** [sitespeedio/sitespeed.io#3585]
When budget gets fail for test execution test is shown as passed.  How to mark test case as failed inside git pipeline.
Refer below snippet:

`# Image contains Chrome Browser. Sitespeed package contains ChromeDriver
image: circleci/node:14.17-bullseye-browsers-legacy
stages:
  - Build
  - Test 
  - Report
`
````yaml
Build:
  stage: Build
  script:
    - npm install 
    - npm install chromedriver --chromedriver-force-download --chromedriver_version=92.0.4515.107
  tags:
    - LAUNCH-HUB
  artifacts:
    paths:     
    - ./node_modules/
  retry:
    max: 1
  allow_failure: true
```
```yaml
AssetManager:
  <<: *artifacts_cache
  stage: Test
  script:
    - ./node_modules/sitespeed.io/bin/sitespeed.js  --config config.json   script/eam/EAM_AppVersionDetails.js --multi -n 1   --cpu  --budget.friendlyName EAM_AppVersionaDetails

  after_script:
    - *copy
  tags:
    - LAUNCH-HUB
  retry:
    max: 1
  allow_failure: true
````

output from git pipeline:
$ ./node_modules/sitespeed.io/bin/sitespeed.js  --config config.json   script/eam/EAM_DistributionVersionDetails.js --multi -n 1   --cpu    --budget.friendlyName EAM_DistributionVersionaDetails
[2022-02-10 01:40:55] INFO: Versions OS: linux 4.14.262-200.489.amzn2.x86_64 nodejs: v14.17.6 sitespeed.io: 19.3.0 browsertime: 14.1.0 coach: 6.4.3
[2022-02-10 01:40:55] INFO: Running tests using Chrome - 1 iteration(s)
[2022-02-10 01:40:56] INFO: Use Chrome trace categories: -*,disabled-by-default-lighthouse,v8,v8.execute,blink.user_timing,devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.stack
[2022-02-10 01:40:56] INFO: Navigating to url https://edge.apps.horizonint.cloud/#/login iteration 1
[2022-02-10 01:41:24] INFO: Start to measure NFR Testing for Distribution Version Details Page
[2022-02-10 01:41:46] INFO: List of Distribution Version Details opened..
[2022-02-10 01:41:47] INFO: No element attached to the entry in largest-contentful-paint
[2022-02-10 01:41:48] INFO: Injecting navigationStart event in the trace log since we could not find any for the most active frame.
[2022-02-10 01:41:50] INFO: https://edge.apps.horizonint.cloud/#/distributionId/e0bb14ab-29d2-4d67-b3a7-[97](https://code.abc.com/horizon/platform-tests/browser-performance/-/jobs/67375568#L97)77cbb31c63/3957e161-c043-4fc7-8b8d-90378d252446 2 requests, TTFB: 1.53s, firstPaint: 1.55s, FCP: 1.95s, DOMContentLoaded: 1.72s, LCP: 4.78s, CLS: 0.0001, TBT: 656ms, Load: 1.75s
[2022-02-10 01:41:50] INFO: Failing budget Total Blocking Time for https://edge.apps.horizonint.cloud/#/distributionId/e0bb14ab-29d2-4d67-b3a7-9777cbb31c63/3957e161-c043-4fc7-8b8d-90378d252446 with value 656 ms max limit 600 ms
[2022-02-10 01:41:50] INFO: Budget: 4 working, 1 failing tests and 0 errors
[2022-02-10 01:41:50] INFO: Write junit budget to /builds/horizon/platform-tests/browser-performance/sitespeed-result/EAM_DistributionVersionDetails_js/2022-02-10-01-40-55/junit.xml
[2022-02-10 01:41:52] INFO: HTML stored in /builds/horizon/platform-tests/browser-performance/sitespeed-result/EAM_DistributionVersionDetails_js/2022-02-10-01-40-55
